[package]
name = "cs140-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cs140-transport = {path="../cs140-transport"}
cpal = "0.13.4"
clap = "2.0.0"
anyhow = "1.0.44"