[package]
name = "cs140-buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cs140-common = {path = "../cs140-common"}
async-trait = "0.1.51"
cpal = "0.13.4"